export const FieldConstants = {
  sections: {
    section: "Section",
    subSection: "Sub-Section",
    closeSection: "Close Section",
  },
  basicFields: {
    singleLine: "Single Line",
    multiLine: "Multi-line",
    checkbox: "Checkbox",
    multipleCheckbox: "Multiple Checkbox",
    radio: "Radio",
    numeric: "Numeric",
    datepicker: "Date picker",
    actionItems: "Action Items",
    paragraph: "Paragraph",
    fileUpload: "File Upload",
    hyperlink: "Hyperlink",
    multipleHyperlink: "Multiple Hyperlink",
    multiplePackaging: "Multiple Packaging",
    approvalCollection: "Approval Collection",
  },
  approvals: {
    qa: "Quality Assurance",
    operations: "Operations",
  },
  lists: {
    standards: "Standards",
    finishedGoods: "Finished Goods",
    lots: "Lots",
    mpis: "MPIs",
    parts: "Parts",
    sops: "SOPs",
    suppliers: "Suppliers",
    custom: "Custom",
  },
};
