export const SHOW_MODAL = "SHOW_MODAL";
export const HIDE_MODAL = "HIDE_MODAL";

export const ADD_FIELD = "ADD_FIELD";
export const EDIT_FIELD = "EDIT_FIELD";
export const UPDATE_FIELD = "UPDATE_FIELD";
export const DELETE_FIELD = "DELETE_FIELD";
export const ADD_LIST = "ADD_LIST";
export const UPDATE_FIELD_VALUE = "UPDATE_FIELD_VALUE";

export const CLOSE_SECTION = "CLOSE_SECTION";
export const RECORD_UPDATES = "RECORD_UPDATES";
export const UPLOAD_TEMPLATE = "UPLOAD_TEMPLATE";

export const SET_FORM_INFO = "SET_FORM_INFO";
export const UPDATE_DRAG_DROP_FIELDS = "UPDATE_DRAG_DROP_FIELDS";
